server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: _logs/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: blog-observability
  static_configs:
  - targets:
      - localhost
    labels:
      job: blog-app-logs
      __path__: _logs/*.log
