server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: _logs/positions.yaml

clients:
  - url: http://grafana.edu.dobias.info:3100/loki/api/v1/push

scrape_configs:
- job_name: student-app-observability
  static_configs:
  - targets:
      - localhost
    labels:
      job: student-app-logs
      __path__: _logs/*.log
